name: hoochat_web #changing it will force you to change appname in import statement inside every .dart file.
description: Web Chats & Calling app

version: 1.0.8+9
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # ---------- 69 direct dependencies last updated on 08/31/2023, 04:49 PM--------------
  webservice: 0.0.6
  flutter_toggle_tab: 1.2.0
  record: 4.4.4
  pin_code_text_field: 1.8.0
  share_plus: 7.1.0
  video_thumbnail_imageview: 0.0.5
  image_downloader_web: 2.0.2
  fast_cached_network_image: 1.2.0
  fluttertoast: 8.0.9
  translator: 0.1.7
  giphy_get: 3.5.0
  file_picker: 5.5.0
  package_info_plus: 4.0.2
  extended_image: 8.1.0
  ffmpeg_kit_flutter: 5.1.0
  logger: 1.4.0
  cloud_functions: 4.4.0
  audioplayers: 5.1.0
  audio_session: 0.1.16
  flutter_emoji: 2.5.1
  cloud_firestore: 4.9.0
  agora_rtc_engine: 5.3.1
  firebase_core: 2.15.1
  font_awesome_flutter: 10.5.0
  video_player: 2.7.0
  geolocator: 10.0.0
  async: 2.11.0
  emoji_picker_flutter: 1.6.1
  group_button: 5.3.3
  http_auth: 1.0.3
  path: 1.8.3
  firebase_storage: 11.2.6
  html: 0.15.4
  diacritic: 0.1.4
  image_cropper: 4.0.1
  flutter_image_compress: 2.0.4
  connectivity_plus: 4.0.2
  crypto: 3.0.3
  dio: 5.3.2
  url_launcher: 6.1.12
  jiffy: 6.2.1
  intl: 0.18.1
  http: 1.1.0
  firebase_auth: 4.8.0
  shared_preferences: 2.2.0
  holding_gesture: 1.2.0
  flutter_linkify: 6.0.0
  image_picker: 1.0.2
  flutter_colorpicker: 1.0.3
  rxdart: 0.27.7
  mime: 1.0.4
  page_transition: 2.0.9
  provider: 6.0.5
  overlay_support: 2.1.0
  encrypt: 5.0.1
  contacts_service: 0.6.3
  string_validator: 1.0.0
  devicelocale: 0.6.0
  percent_indicator: 4.2.3
  wakelock_plus: 1.1.1
  flutter_secure_storage: 8.0.0
  oktoast: 3.3.1
  flutter_sound: 9.2.13
  file_saver: 0.1.1
  random_string: 2.3.1
  flutter_native_timezone: 2.0.0
  photo_view: 0.14.0
  circular_countdown_timer: 0.2.3
  # ---------- end of direct dependencies --------------

  camera: 0.10.5+3
  otp_pin_field: 1.2.2
  scoped_model: 2.0.0
  universal_platform: 1.0.0+1
  localstorage: 4.0.1+4
  dotted_border: 2.0.0+3
  pip_view: 0.9.7

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
  flutter_driver:
    sdk: flutter
  test: ^1.16.8
dependency_overrides:
  http: "0.13.4"
  dio: "4.0.6"

  flutter_launcher_icons: ^0.9.0
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/appicon/appicon.jpg"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/flags/
    - lib/Services/localization/json_languages/
